title: Wimlib-Imagex-Package
description: Wimlib-Imagex for macOS. Working from macOS Catalina 10.15 to macOS Ventura 13
github:
  repository_url: https://github.com/chris1111/Wimlib-Imagex-Package
remote_theme: chris1111/cayman-dark
